version: "3"

services:
  nodeserver:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: minha_grade_UFRB
    depends_on:
      - db
    command: sh -c "yarn dev"
    ports:
      - "8000:3111" #<port where container are>:<port to app in container>
    environment:
      DATABASE_URL: postgresql://docker:docker@db:5432/minhagrade?schema=public
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules
      - /usr/app/prisma
    networks:
      - app-network

  reactfront:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: front_ngnix
    ports:
      - "80:80"

  crawler_s:
    build:
      context: ./pdf_to_json_service
      dockerfile: ./Dockerfile
    container_name: pdf_to_json_service
    ports:
      - "8090:8000" #<port where container listen>:<port where the app are in container>

  db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: minhagrade
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
