version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile
    container_name: minha_grade
    depends_on:
      - db
    command: sh -c "npm start"
    ports:
      - "3333:3000"
    environment:
      DATABASE_URL: postgresql://docker:docker@db:5432/minhagrade?schema=public
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/prisma
    networks:
      - app-network

  db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: minhagrade
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
