version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfiles/DockerfileBack
    container_name: minha_grade_UFRB
    depends_on:
      - db
    command: sh -c "yarn dev"
    ports:
      - "3111:3111"
    environment:
      DATABASE_URL: postgresql://docker:docker@db:5432/minhagrade?schema=public
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/prisma
    networks:
      - app-network

#  apache:
#    image: httpd:latest
#    build:
#      context: .
#      dockerfile: ./Dockerfiles/DockerfileApache
#    container_name: apache-server
#    ports:
#    - '80:80' #listen on 80
    #command: a2enmod proxy; /etc/init.d/apache2 restart
    #volumes:
    #- /usr/local/apache2/conf/ :conf/httpd.conf

  db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: minhagrade
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
